### ISSUE TITLE
Enchanted book not found

### ISSUE THREAD

**Issue by Lymno** [Mikndesu/LavaWalkerMod#21]
Hi, I'm using the latest Fabric 1.21.1 version of the mod. In fact, it doesn't work at all, I can't find this enchantment. But I can see this mod in the modmenu.

**Comment by Mikndesu** [comment]
Hi, Lymno. Thank you for your report. I'll address this issue by the end of the day.

**Comment by Mikndesu** [comment]
I've replaced fabric 3.0.0 mod-file with what resolves the issue. Hope you like it!
